name: Chocolatine
on:
  push:
    branches-ignore:
      - " ga-ignore-"
  pull_request:
    branches-ignore:
      - " ga-ignore-"
env:
   MIRROR_URL: git@github.com:EpitechPGEPromo2029/B-DOP-200-COT-2-1-chocolatine-ridwane.nico.git
   EXECUTABLES: 105demography

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - run: check.sh $(pwd) $(pwd)

  check_compilation:
    needs: check_coding_style
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - run: make || { echo "Erreur de compilation"; exit 1; }
      - run: make clean

  run_tests:
    needs: check_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - run: make tests_run || { echo "Echec des tests"; exit 1; }
      - run: make clean

  mirroir:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ env.MIRROR_URL }}
        ssh_private_key:
          ${{ secrets.GIT_SSH_PRIVATE_KEY }}
